type Mv {
   orderId: Int!
   text: String!
   story: String
   author: String
   timestamp: Int
}
type Query {
   allMvs: [Mv!]
   mv(id: Int!): Mv
   mvByAuthor(author: String!): [Mv!]
   mvByOrderId()
}